- docs/AboutUs.md
- docs/team/tankh99.md
Adds my info into the team about
> Add member info

- README.md
- docs/AboutUs.md
Aims to resolve the following issues from the tP tracker
> Update links in README and remove placeholder text

- build.gradle
add the requirement into gradle build.
> Fix import JavaFX media error

- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Currently when the application is closed and re-opened, the Id of the student is discarded and start from 1 again. This makes it such that it is unable to guarantee uniqueness of the Id field. This PR aims to resolve this issue by reading, and incrementing the Id of the last student that was stored in the JSON file.
> Continue from previous elapsed Id

- .github/pull_request_template
Fixes: trailing white space error
Delete it
> Delete trailing whitespace in pr template

- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Aims to resolve #33. In the original AB3 deletion of student is done in the intrinsic ordering of the list. However, our application aims to resolve this by ensuring data integrity. Every student is tagged with an increasing integer identifier to guarantee uniqueness.
> Delete students based on Student Id

- src/test/java/seedu/address/logic/LogicManagerTest.java
Fixes:
Storage Test Issue
by adding Temp AppointmentList.json address
> Fix Storage Test Issue

- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/TypicalIndexes.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
1. Tests deletion by studentId, rather than natural ordering of students.
> Add test cases for students

- docs/diagrams/BetterAppointmentClassDiagram.puml
Fixes: 
Add new BetterAppointmentClassDiagram. Class diagram is as attached
> Add BetterAppointmentClassDiagram

- docs/diagrams/ModelClassDiagram.puml
- docs/diagrams/StorageClassDiagram.puml
> Update UML Diagram

- docs/UserGuide.md
> Fix user guide bugs

- docs/diagrams/ArchitectureDiagram.puml
Updated architecture diagram to make more logical sense rather than strictly follow the current proje ct structure
> Update Architecture Diagram

- docs/diagrams/ModelClassDiagram.puml
> Rearrange UML Diagram

- src/main/resources/view/MainWindow.fxml
> Rename title bar

- src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
> Add test logging to AddPatientCommandParser

- src/main/java/seedu/address/logic/commands/HelpCommand.java
- src/main/java/seedu/address/ui/MainWindow.java
Fixes: #30.  Makes it more similar to our v1.2 draft.
Fixes: #127. Help window now automatically un-minimize when you perform the same set of steps.
@vnnamng will need your help to test out please.
> Improve Help message

- src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
Fixes: #120
Reorder add appointment command validation checks
> Fix appointment index not increasing when wrongly created

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/FilterAppointmentCommand.java
- src/main/java/seedu/address/logic/parser/FilterAppointmentCommandParser.java
- src/main/java/seedu/address/logic/parser/PatientListParser.java
- src/main/java/seedu/address/model/appointment/Appointment.java
- src/main/java/seedu/address/model/appointment/FilterAppointmentPredicate.java
- src/main/java/seedu/address/storage/JsonSerializableAppointmentList.java
- src/test/java/seedu/address/logic/commands/FilterAppointmentCommandTest.java
- src/test/java/seedu/address/testutil/TypicalAppointments.java
- src/test/java/seedu/address/testutil/TypicalEndDateTime.java
- src/test/java/seedu/address/testutil/TypicalStartDateTime.java
Add appointment filter command:
filterappointment sd/START_DATE_TIME ed/END_DATE_TIME
check for START_DATE_TIME <= END_DATE_TIME
> filter appointment by date range

- src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
- src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
- src/main/java/seedu/address/model/appointment/Appointment.java
- src/main/java/seedu/address/storage/JsonSerializableAppointmentList.java
Add exceptions for end date < start date.
Update add appointment messages.
> Fix Add Appointment checks for StartDateTime and EndDateTime

- docs/UserGuide.md
Fixes: #128 
- As mentioned in the title
- Also changed sid to pid
> Refactor all student instances to patient in UG

- src/main/java/seedu/address/model/appointment/Appointment.java
- src/main/java/seedu/address/model/appointment/DateTimeField.java
- src/test/java/seedu/address/model/appointment/DateTimeFieldTest.java
> Change DateTimeField check implementation

- src/main/java/seedu/address/logic/commands/DeleteCommand.java
Delete a patient will delete all appointment that is linked to that patient.
> Add Cascade delete for Patient Delete Command

- src/main/java/seedu/address/logic/parser/ListAppointmentCommandParser.java
- src/main/java/seedu/address/logic/parser/ListPatientCommandParser.java
- src/test/java/seedu/address/logic/parser/PatientListParserTest.java
`querystudents asdasd` or `queryappointments sdauhsdj` now display error
> Fix query commands

- src/main/java/seedu/address/logic/commands/ReportFeedbackCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/appointment/FeedbackScore.java
- src/main/java/seedu/address/model/patientfeedbackreport/PatientFeedbackReport.java
- src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
- src/main/java/seedu/address/ui/AppointmentCard.java
- src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
- src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
Fixes: #159 
1. Change type of feedbackScore from int to Integer as well as all dependencies that use this field
2. Update the test to return true if feedbackScore is null
3. Fix GUI to hide if nujll
4. Also removed a useless function that essentially just updated appointments
> Fix nullable feedback score

- docs/UserGuide.md
> Update UG Documentation (Jerome)

- src/main/java/seedu/address/logic/commands/FilterAppointmentCommand.java
- src/main/java/seedu/address/logic/parser/FilterAppointmentCommandParser.java
- src/main/java/seedu/address/model/appointment/DateTimeField.java
- src/main/java/seedu/address/model/appointment/FilterAppointmentPredicate.java
- src/test/java/seedu/address/logic/commands/FilterAppointmentCommandTest.java
> Update Filter Command (new PR)

- src/main/java/seedu/address/logic/commands/AddPatientCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
> Simplify commands

- src/main/java/seedu/address/ui/AppointmentListViewCell.java
- src/main/java/seedu/address/ui/ListPanel.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/java/seedu/address/ui/PersonListViewCell.java
Fixes:
https://github.com/AY2324S2-CS2103-F08-2/tp/assets/86278971/e259fa48-be6d-4101-8282-45c4d53244ac
> Fix GUI bug

- src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
This fixes a bug where if user didn't add end date time, the program would quickly crash
> Check for end date time

- src/main/java/seedu/address/model/patientfeedbackreport/PatientFeedbackReport.java
FeedbackScore was nullable, but there was no check regarding that
> Add null check for getAvgFeedbackScore

- src/main/java/seedu/address/commons/util/DateUtil.java
- src/main/java/seedu/address/logic/Messages.java
- src/test/java/seedu/address/commons/util/DateUtilTest.java
Fixes: #276 
Fixes #273 
1. Fixes issue with 30 Feb 2024 being a possible date
2. Formats appointment dates correctly now
> Fix lenient date time parsing and formatting issue

- docs/DeveloperGuide.md
- docs/diagrams/ReportFeedbackSequenceDiagram.puml
- src/main/java/seedu/address/model/patientfeedbackreport/PatientFeedbackReport.java
Fixes #303 
Fixes #310 
Fixes #212 
1. Add implementation details for patient feedback report
2. Add missing use cases for patient feedback report
3. Add missing diagrams for command history and patient feedback report into DG
4. Add report feature into the user story
5. Add report feedback sequence diagram
> Add feedback report implementation and use case

- src/main/java/seedu/address/logic/parser/ListAppointmentCommandParser.java
> Add check to ensure only no duplicate prefix

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/model/patient/Patient.java
- src/main/java/seedu/address/model/patient/TagContainsKeywordPredicate.java
- src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
Fixes #315 Removed width of UML diagram
Removed some todos from Jerome
Fixes #243 changed ordering of UG
Fixes #268 indicated in UG that 0 is not a valid value..
> Remove Jerome's todos (partial)

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/diagrams/ArchitectureDiagram.puml
- docs/diagrams/ArchitectureSequenceDiagram.puml
- docs/diagrams/EditAppointmentSequenceDiagra.puml
- docs/diagrams/FilterAppointmentSequenceDiagram.puml
- docs/diagrams/HelpCommandSequenceDiagram.puml
- docs/diagrams/UiClassDiagram.puml
- src/main/java/seedu/address/ui/AppointmentCard.java
- src/main/java/seedu/address/ui/PatientFeedbackReportCard.java
- src/main/java/seedu/address/ui/PersonCard.java
Fixes: #183
Fixes: #274 
1. Added clarification that we only accept singaporean numbers in UG
2. Rename PatientListParser to CommandParser
3. Update diagrams
4. Fix text wrapping
> General Refactor (KH)

- docs/UserGuide.md
- src/main/java/seedu/address/model/tag/Tag.java
Fixes: #281 Naming inconsistencies
Fixes: #264 Error message bug
> Resolve Tag naming inconsistency

- src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
- src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/FilterAppointmentCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/ListAppointmentCommand.java
- src/main/java/seedu/address/logic/commands/ReportFeedbackCommand.java
I am too scared to add other parts, which may break the code
> Add Assertion for Commands

- docs/diagrams/EditAppointmentSequenceDiagram.puml
- docs/diagrams/FilterAppointmentSequenceDiagram.puml
- docs/diagrams/HelpCommandSequenceDiagram.puml
> Update DG 1.4a part 2

- docs/diagrams/FindPatientSequenceDiagram.puml
> Update UML diagrams (Jerome)

- src/main/java/seedu/address/logic/parser/ReportFeedbackCommandParser.java
- src/main/java/seedu/address/model/appointment/HasAttended.java
- src/main/java/seedu/address/model/patientfeedbackreport/PatientFeedbackReport.java
> Rename boolean variables

- docs/DeveloperGuide.md
- docs/diagrams/QueryAppointmentActivityDiagram.puml
- docs/diagrams/QueryAppointmentSequenceDiagram.puml
- docs/diagrams/ReportFeedbackSequenceDiagram.puml
- docs/diagrams/command-history/CommandHistoryRedoActivityDiagram.puml
- docs/diagrams/command-history/CommandHistoryUndoActivityDiagram.puml
1. Adds diagrams for query appointment
2. Adds DG section for query appointment
3. Fixes other diagrams as well
> Update command history illustration and formatting

- src/main/java/seedu/address/ui/AppointmentCard.java
- src/main/java/seedu/address/ui/PatientFeedbackReportCard.java
- src/main/java/seedu/address/ui/PersonCard.java
This reverts commit 7f93eca6d41928770c687f39c6845c97ca4d301c.
This commit involved adding text wrapping capabilities. However, this violates the feature freeze so I'm reverting it
> Revert "Fix name text wrapping in card"

- docs/DeveloperGuide.md
Change patient case log to appointment note i,e appointment description
> Remove case log mention in DG

- docs/DeveloperGuide.md
- docs/diagrams/AddAppointmentActivityDiagram.puml
- docs/diagrams/DeleteAppointmentActivityDiagram.puml
Fixes: #338 
1. Updates Instructions for manual testing section in DG
2. Update activity diagrams
> Update instructions for manual testing in dg

- docs/UserGuide.md
Makes some general updates and fixes
> Update validation sections

- docs/DeveloperGuide.md
> Improve English

- docs/DeveloperGuide.md
- docs/diagrams/ArchitectureDiagram.puml
- docs/diagrams/DeletePatientSequenceDiagram.puml
- docs/diagrams/EditAppointmentSequenceDiagram.puml
- docs/diagrams/ReportFeedbackSequenceDiagram.puml
- src/main/java/seedu/address/commons/util/AudioUtil.java
Fixes stupid issues
1. Delete patinet sequence diagram
1. [x] Remove activation bar in delete patient sequence diagram
2. [x] Remove excessive function calls in delete patient sequence diagram
3. [x] Shorten commands
4. [x] There is a duplicate diagram for deleting patient
2. Edit appointment seq diagram
1. [x] typo in updateFilterAppointmentList
3. Remove unused command result 
4. [x] Re-add commons into the architecture diagram
5. [x] ReportFeedbackCommandSeqDiagram - Remove the cross at the command
6. [x] Typo 'PatientFEedbackReportList'
7. [x] Add code reference for audio Util
8. [x] Remove "sort patients based on priority tag"
> Update DG (KH)

- docs/diagrams/QueryAppointmentSequenceDiagram.puml
As above, also updated query appt
> Remove destruction of command in query appointment

- docs/UserGuide.md
> Fix typos in UG
